- hosts: all
  become: true
  tasks:  
    - name: Update System
      apt: 
        update_cache: yes
        upgrade: yes

    - name: Install minimal required libraries with apt
      apt: 
        name: "{{ packages }}"
      vars:
        packages:
        - alsa-utils
        - htop
        - bzip2
        - gzip
        - p7zip
        - unzip
        - mlocate
        - ntfs-3g
        - dosfstools
        - wget
        - rxvt-unicode
        - gawk
        - zsh
        - vim
        - openssh-server
        - bluetooth

    - name: Enable ZSH
      shell: chsh -s $(which zsh) $SUDO_USER

