- hosts: all
  tasks:  
    - name: Set locales
      vars:
          locale: en_BE.UTF-8
          parameters:
            - LC_MEASUREMENT
            - LC_MONETARY
            - LC_NUMERIC
            - LC_TIME
      block:
        - shell: >
            kwriteconfig5
            --file plasma-localerc
            --group Formats
            --key {{ item }}
            "{{ locale }}"
          loop: "{{ parameters }}"
        - replace:
            path: /home/{{ ansible_user_id }}/.config/plasma-locale-settings.sh
            regexp: 'export {{ item }}=.*'
            replace: 'export {{ item }}={{ locale }}'
          loop: "{{ parameters }}"


    - name: Disable logout confirmation
      shell: >
          kwriteconfig5 
          --file ksmserverrc 
          --group General
          --key confirmLogout
          --type bool
          false

    - name: Login with empty session
      shell: >
          kwriteconfig5 
          --file ksmserverrc 
          --group General
          --key loginMode
          default
    - name: Disable Splash
      shell: >
          kwriteconfig5 
          --file ksplashrc
          --group KSplash
          --key Engine
          none

    - name: Disable Splash
      shell: >
          kwriteconfig5 
          --file ksplashrc
          --group KSplash
          --key Theme
          None

    - name: Set SDDM Wallpaper
      become: yes
      block:
        - replace:
            path: /usr/share/sddm/themes/ubuntu-theme/theme.conf
            regexp: background=.*
            replace: background=/home/{{ ansible_user_id }}/Wallpapers/SDDM/background.png
        - replace:
            path: /usr/share/sddm/themes/ubuntu-theme/theme.conf.user
            regexp: background=.*
            replace: background=/home/{{ ansible_user_id }}/Wallpapers/SDDM/background.png

    - name: Install Kvantum
      block:
        - apt:
            name: libvulkan1=1.1.101.0-2
          become: yes
        - apt:
            name: "{{ packages }}" 
            state: latest
          become: yes
          vars: 
            packages:
            - g++ 
            - libx11-dev 
            - libxext-dev 
            - qtbase5-dev 
            - libqt5svg5-dev 
            - libqt5x11extras5-dev 
            - libkf5windowsystem-dev 
            - qttools5-dev-tools 
            - cmake 
            - checkinstall
        - git:
            repo: https://github.com/tsujan/Kvantum
            dest: /tmp/kvantum
        - file: 
            path: /tmp/kvantum/Kvantum/build
            state: directory
        - shell: cmake ..
          args:
            chdir: /tmp/kvantum/Kvantum/build
        - make:
            chdir: /tmp/kvantum/Kvantum/build
        - make: 
            chdir: /tmp/kvantum/Kvantum/build
            target: install
          become: yes

    - name: Configure Materia
      tags: rice
      block:
        - name: Add Materia repo
          become: yes
          apt_repository: 
            repo: ppa:papirus/papirus
        - name: Install Materia
          become: yes
          apt:
            name: materia-kde
            state: latest
            update_cache: yes
            install_recommends: yes
        - name: Link Materia theme
          file:
            src: /usr/share/Kvantum/Materia
            state: link
            dest: /home/{{ ansible_user_id }}/.config/Kvantum/Materia
            force: yes
        - name: Link Materia Dark theme
          file:
            src: /usr/share/Kvantum/MateriaDark
            state: link
            dest: /home/{{ ansible_user_id }}/.config/Kvantum/MateriaDark
            force: yes
        - name: Install Materia in Kvantum
          shell: kvantummanager --set MateriaDark

    - name: Configure Papirus Icon Pack
      block: 
        - name: Add Papirus repo
          become: yes
          apt_repository: 
            repo: ppa:papirus/papirus
        - name: Install Papirus
          become: yes
          apt:
            name: papirus-icon-theme
            state: latest
            update_cache: yes
            install_recommends: yes

    - name: Install Simple Menu
      block:
        - name: Download simple menu
          git:
              repo: https://github.com/KDE/plasma-simplemenu/
              dest: /tmp/simple_menu
        - name: Ensure widget folder exists
          file:
              path: /home/{{ ansible_user_id }}/.local/share/plasma/plasmoids/org.kde.plasma.simplemenu
              state: directory
        - name: Extract simple menu
          copy:
              src: /tmp/simple_menu/package/
              dest: /home/{{ ansible_user_id }}/.local/share/plasma/plasmoids/org.kde.plasma.simplemenu

    - name: Install Event Calendar
      block:
        - name: Download Event Calendar
          git:
              repo: https://github.com/Zren/plasma-applet-eventcalendar.git
              dest: /tmp/eventcalendar
              force: yes
        - name: Make installer executable
          file: 
            dest: /tmp/eventcalendar/install
            mode: a+x
        - name: Install Event Calendar
          shell: ./install
          ignore_errors: yes
          args:
            chdir: /tmp/eventcalendar

    - name: Set Screen Locker to Materia
      shell: >
          kwriteconfig5 
          --file kscreenlockerrc
          --group Greeter
          --key Theme
          com.github.varlesh.materia
    - name: Set Screen Locker Background
      shell: >
          kwriteconfig5 
          --file kscreenlockerrc
          --group Greeter
          --group Wallpaper
          --group org.kde.image
          --group General
          --key Image
          "file:///home/{{ ansible_user_id }}/Wallpapers/SDDM/background.png"
    - name: Set Icon Pack to Papirus
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group Icons
          --key Theme
          Papirus
    - name: Set Plasma Shell to Materia
      shell: >
          kwriteconfig5 
          --file plasmarc
          --group Theme
          --key name
          Materia
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group General
          --key Name
          Materia Dark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group General
          --key ColorScheme
          MateriaDark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group KDE
          --key ColorScheme
          MateriaDark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group KDE
          --key LookAndFeelPackage
          com.github.varlesh.materia
    - name: Set Widget Style to kvantum
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group KDE
          --key widgetStyle
          kvantum
    - name: Set Widget Style to kvantum
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group General
          --key widgetStyle
          kvantum

