version: "2.3"

services:
#https://github.com/pi-hole/docker-pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: "Europe/Brussels"
      ServerIP: 172.16.1.194
      DNS1: 1.1.1.1
    volumes:
      - '/drive/DockerConfigs/Pihole/Config/:/etc/pihole/'
      - '/drive/DockerConfigs/Pihole/ConfigDNSMasq/:/etc/dnsmasq.d/'
    networks:
      pihole_macvlan:
        ipv4_address: 172.16.1.194
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1

networks:
  pihole_macvlan:
    name: pihole_macvlan
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config: 
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
          ip_range: 172.16.1.192/26
          aux_addresses: 
            host1: 172.16.1.192
            host2: 172.16.1.193

