version: "3"

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    depends_on:
      - deluge
      - syncthing
      - airsonic
      - freshrss
      - netdata
      - plik
      - organizr
      - portainer
      - headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - URL=confusedhobo.ddns.net
      - VALIDATION=http
    volumes:
      - /drive/LetsEncrypt/Config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  nginx:
    image: linuxserver/nginx
    container_name: nginx 
    cap_add:
      - NET_ADMIN
    depends_on:
      - deluge
      - syncthing
      - airsonic
      - freshrss
      - netdata
      - plik
      - organizr
      - portainer
      - headphones
      - firefly-db
      - firefly
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Nginx/Config:/config
    ports:
      - 80:80
    restart: unless-stopped
#https://github.com/pi-hole/docker-pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      TZ: "Europe/Brussels"
      ServerIP: 10.0.1.30
    volumes:
      - '/drive/Pihole/Config/:/etc/pihole/'
      - '/drive/Pihole/ConfigDNSMasq/:/etc/dnsmasq.d/'
    restart: unless-stopped

  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Organizr/Config:/config
    ports:
      - 8000:80
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Portainer/Config:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8010:8000
      - 8011:9000
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    environment:
      - PUID=1000
      - PGID=999
      - TZ=Europe/Brussels
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports: 
      - 8020:19999
    restart: unless-stopped

  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /drive/OpenVPN/Config:/config
    ports:
      - 8030:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped


  headphones:
    image: linuxserver/headphones
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Headphones/Config:/config
      - /drive/Headphones/Downloads:/downloads
      - /drive/MusicOrganized:/music
    ports:
      - "8100:8181"
    restart: unless-stopped

  beets:
    image: linuxserver/beets
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Beets/Config:/config
      - /drive/MusicOrganized:/music
      - /drive/MusicReOrganized:/musicnew
      - /drive/MusicUnorganized:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped

  lms:
    container_name: lms
    #    image: larsks/logitech-media-server
    image: snoopy86/logitechmediaserver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /drive/LMS/config:/config
      - /drive/MusicOrganized:/srv/music
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8110:9000
      - 9090:9090
      - 3483:3483
      - 3483:3483/udp
    devices:
      - /dev/snd
    restart: always
    #    command: 
    #  - '1000'

  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - CONTEXT_PATH=/
    volumes:
      - /drive/Airsonic/Config:/config
      - /drive/MusicOrganized:/music
      - /drive/Airsonic/Playlists:/playlists
      - /drive/Airsonic/Podcasts:/podcasts
      - /drive/Airsonic/Media:/media
    ports:
      - 8120:4040
    restart: unless-stopped


  firefly: 
    image: jc5x/firefly-iii
    container_name: firefly 
    environment: 
      - FF_DB_HOST=firefly-db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=Europe/Brussels
      - APP_LOG_LEVEL=debug
      - TRUSTED_PROXIES=**
    links: 
      - firefly-db
    volumes: 
      - /drive/FireflyIII/Export:/var/www/firefly-iii/storage/export
      - /drive/FireflyIII/Upload:/var/www/firefly-iii/storage/upload
      - /drive/FireflyIII/Config/.env:/var/www/firefly-iii/.env
    ports:
      - 8200:80

  firefly-db: 
    container_name: firefly-db
    environment: 
      - POSTGRES_PASSWORD=firefly
      - POSTGRES_USER=firefly
    image: "postgres:10"
    volumes: 
      - /drive/FireflyIII/Data:/var/lib/postgresql/data

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Syncthing/Config:/config
      - /drive/Syncthing/Data:/data
    ports:
      - 8210:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    depends_on:
      - firefly-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/FreshRSS/Config:/var/www/
    ports:
      - 8220:80
    restart: unless-stopped

  plik:
    image: rootgg/plik:latest
    container_name: plik
    user: 1000:1000
    volumes:
      - /drive/Plik/Data:/home/plik/server/files
      - /drive/Plik/plikd.cfg:/home/plik/server/plikd.cfg
    ports:
      - 8230:8080
    tty: true

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/Deluge/Config:/config
      - /drive/Deluge/Downloaded:/downloads
    restart: unless-stopped

